1. [Glossary](#glossary)
2. [Overview of Steps for Network Participants](#overview-of-steps-for-network-participants)
3. [Introduction](#introduction)
   1. [Introduction to Open Networks](#introduction-to-open-networks)
      1. [What is an Open Network?](#what-is-an-open-network)
      2. [Advantages of Connecting to an Open Network](#advantages-of-connecting-to-an-open-network)
      3. [What Does an Open Network Look Like?](#what-does-an-open-network-look-like-include-details-about-the-landscape)
      4. [Different Roles in an Open Network](#different-roles-in-an-open-network)
         1. [Beckn Application Platforms (BAP)](#beckn-application-platforms-bap)
         2. [Beckn Provider Platforms (BPP)](#beckn-provider-platforms-bpp)
         3. [Network Facilitator](#network-facilitator)
         4. [Technical Service Provider (TSP)](#technical-service-provider-tsp)
4. [Brief Introduction to Beckn Network](#brief-introduction-to-beckn-network)
   1. [Different APIs](#different-apis)
   2. [Schema](#schema)
   3. [API Mapping](#api-mapping)
   4. [Beckn Developer Documentation](#beckn-developer-documentation)
5. [Learning Resources](#learning-resources)
6. [Getting Started with Beckn](#getting-started-with-beckn)
   1. [Introduction](#introduction-1)
      1. [Different Roles in an Open Network](#different-roles-in-an-open-network-1)
         1. [Beckn Application Platforms (BAP)](#beckn-application-platforms-bap-1)
         2. [Beckn Provider Platforms (BPP)](#beckn-provider-platforms-bpp-1)
         3. [Network Facilitator](#network-facilitator-1)
         4. [Technical Service Provider (TSP)](#technical-service-provider-tsp-1)
   2. [Identify Your Role](#identify-your-role)
   3. [Define Your Requirements and Success Definition Clearly - Outcome Visualization](#define-your-requirements-and-success-definition-clearly---outcome-visualization)
   4. [Map Your Journey as per the Role Selected & Outcome Visualization](#map-your-journey-as-per-the-role-selected--outcome-visualization)
7. [Network Participant's Journey](#network-participants-journey)
   1. [Seeker Platform's Journey](#seeker-platforms-journey)
      1. [Unbundle Your Platform](#unbundle-your-platform)
         1. [Help NP Visualize What an Unbundled or Decentralized Application Is](#help-np-visualize-what-an-unbundled-or-decentralized-application-is)
         2. [Monolithic vs. Unbundled Application](#monolithic-vs-unbundled-application)
            - [Unbundling Process](#unbundling-process)
         3. [Note on How Fast an NP Can Unbundle its App Using Protocol Server (Existing Open Source Assets)](#note-on-how-fast-an-np-can-unbundle-its-app-using-protocol-server-existing-open-source-assets)
         4. [Explanation About Beckn Adapter](#explanation-about-beckn-adapter)
         5. [Details on How Beckn Adapter Will Help in Unbundling the Existing Application](#details-on-how-beckn-adapter-will-help-in-unbundling-the-existing-application)
         6. [Details About the Open-Source Beckn Adapter (Protocol Server)](#details-about-the-open-source-beckn-adapter-protocol-server)
         7. [Landscape Overview](#landscape-overview)
         8. [Technical Details Related to an Adapter](#technical-details-related-to-an-adapter)
            1. [Header Signature](#header-signature)
            2. [Beckn Endpoints](#beckn-endpoints)
         9. [Explanation of Protocol Server Architecture and Different Components](#explanation-of-protocol-server-architecture-and-different-components)
         10. [Connecting the Application to the Adapter After Deploying the Protocol Server](#connecting-the-application-to-the-adapter-after-deploying-the-protocol-server)
         11. [DNS Names Details](#dns-names-details)
         12. [Registering in the Registry](#registering-in-the-registry)
         13. [Using Postman Collection for End-to-End Testing Using Beckn Sandbox](#using-postman-collection-for-end-to-end-testing-using-beckn-sandbox)
      2. [Schema Mapping](#schema-mapping)
      3. [Deploying Protocol Server (Using ONIX)](#deploying-protocol-server-using-onix)
      4. [Understanding the Beckn Application Platforms (BAP) APIs (Link Domain-specific Implementation Guides)](#understanding-the-beckn-application-platforms-bap-apis-link-domain-specific-implementation-guides)
      5. [Test Your APIs](#test-your-apis)
      6. [Sandbox for Network Participants](#sandbox-for-network-participants)
   2. [Provider Platform's Journey](#provider-platforms-journey)
      1. [Unbundle Your Platform](#unbundle-your-platform-1)
      2. [Schema Mapping](#schema-mapping-1)
      3. [Deploying Protocol Server (Using ONIX)](#deploying-protocol-server-using-onix-1)
      4. [Understanding the Beckn Provider Platforms (BPP) APIs (Link Domain-specific Implementation Guides)](#understanding-the-beckn-provider-platforms-bpp-apis-link-domain-specific-implementation-guides)
      5. [Test Your APIs](#test-your-apis-1)
   3. [Network Facilitator Journey](#network-facilitator-journey)
      1. [Setting Up Gateway and Registry](#setting-up-gateway-and-registry)
      2. [DNS Mapping](#dns-mapping)
      3. [Rolling Out a Form for NP Onboarding](#rolling-out-a-form-for-np-onboarding)
      4. [Setting Up Sandbox, Pre-Prod, and Prod Environments](#setting-up-sandbox-pre-prod-and-prod-environments)
   4. [Troubleshooting Guide](#troubleshooting-guide)
8. [Implementation](#implementation) - This section is managed through an Implementation Guide
   1. [Provide a Brief About Different Domains and Use Cases and Link to the IG](#provide-a-brief-about-different-domains-and-use-cases-and-link-to-the-ig)
   2. [Sample Implementation Guides](#sample-implementation-guides)
   3. [Concept of Your Application](#concept-of-your-application)
   4. [API Integration](#api-integration)
      1. [Understand the APIs](#understand-the-apis)
      2. [Building and Integrating the Seeker Platform](#building-and-integrating-the-seeker-platform)
      3. [Building and Integrating the Beckn Provider Platforms (BPP)](#building-and-integrating-the-beckn-provider-platforms-bpp)
9. [Going to Production](#going-to-production)
   1. [Pre-Production](#pre-production)
   2. [Production Preparedness](#production-preparedness)
   3. [Go Live](#go-live)
10. [Migrating to Beckn-ONIX from Existing Implementation](#migrating-to-beckn-onix-from-existing-implementation)
11. [Migrating from an Old Version of Beckn API to a New Version](#migrating-from-an-old-version-of-beckn-api-to-a-new-version)
12. [Beckn FAQ](#beckn-faq)
13. [Seeking Help](#seeking-help)
    1. [Join an Existing Community / Discord Channel](#join-an-existing-community--discord-channel)
    2. [Tech Office Hours](#tech-office-hours)
       1. [Tuesday: 3:30 PM IST](#tuesday-330-pm-ist)
       2. [Thursday: 8:30 PM IST](#thursday-830-pm-ist)
    3. [GitHub Discussions / Forums](#github-discussions--forums)
14. [Resources](#resources)
    1. [List All Relevant GitHub Repos](#list-all-relevant-github-repos)
15. [Beckn Tool Kit](#beckn-tool-kit)
    1. [Link to Experience Centre](#link-to-experience-centre)
    2. [Link to Reference Applications](#link-to-reference-applications)
16. [References](#references)
    1. [Link to Beckn Website](#link-to-beckn-website)

